### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by quangm2k2** [IronKinoko/e-hentai-view#1]
How can i login?
It always says "login failed"

**Comment by IronKinoko** [comment]
> How can i login?
> It always says "login failed"

now, you can try again, i had fixed many bugs

**Comment by quangm2k2** [comment]
> > How can i login?
> > It always says "login failed"
> 
> now, you can try again, i had fixed many bugs

Thank you so much, but now it says "**no login**" T.T

**Comment by IronKinoko** [comment]
> > > How can i login?
> > > It always says "login failed"
> > 
> > 
> > now, you can try again, i had fixed many bugs
> 
> Thank you so much, but now it says "**no login**" T.T

emm.... it just like the cookie you got from login is incorrect
Can you visit exhentai directly? 
Maybe you can try to sign in with cookies

**Comment by quangm2k2** [comment]
╰(*°▽°*)╯
