### ISSUE TITLE
Where is a piece of JavaScript code

### ISSUE THREAD

**Issue by aeongdesu** [IronKinoko/e-hentai-view#11]
![image](https://user-images.githubusercontent.com/50764666/94357868-7375ca00-00d7-11eb-876a-4a830fcbb634.png)

**Comment by IronKinoko** [comment]
Sorry!!!!!!
Not finished yet.   lol :)

**Comment by IronKinoko** [comment]
Now I provide the JavaScript code and update the documentation.
You can [see here](https://raw.githubusercontent.com/IronKinoko/asset/master/e-hentai-view/fixChromeExhentaiCookie.js)
@KeepSOBP

**Comment by aeongdesu** [comment]
Thanks
