### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by aeongdesu** [IronKinoko/e-hentai-view#17]
## add cookie tutorial for mobile
![image](https://user-images.githubusercontent.com/50764666/95681987-dc078f80-0c1d-11eb-8c8f-91d355cbd2f3.png)

Not easy to edit cookies on mobile(ios, android), so needs tutorial or other

## Tag info i18n support 
![image](https://user-images.githubusercontent.com/50764666/95682094-6a7c1100-0c1e-11eb-96a2-4519ff988403.png)
yea chinese based

## Change reading direction button to list

Change reading direction button to list like ehviewer because i18n langs
![image](https://user-images.githubusercontent.com/50764666/95682242-35bc8980-0c1f-11eb-87c6-13907f2f0ae5.png)
![image](https://user-images.githubusercontent.com/50764666/95682277-5f75b080-0c1f-11eb-9499-5451e6689b6f.png)

**Comment by IronKinoko** [comment]
# 1. add cookie tutorial for mobile

I will add the cookie solution only for IOS.

Android has no good solution, recommends using [seven332/EhViewer](https://github.com/seven332/EhViewer).

# 2. Tag info i18n support

Tag info is based on this repo([EhTagTranslation/Database](https://github.com/EhTagTranslation/Database/tree/master/database)), and only supports Chinese.

 I will remove these tips when it is not in Chinese

# 3. Change reading direction button to list

I will add this feature in the update plan.

**Comment by aeongdesu** [comment]
Thank you!
