### ISSUE TITLE
Cookies Samesite Workarounds (that works for now) for Chrome on Android

### ISSUE THREAD

**Issue by Nicezki** [IronKinoko/e-hentai-view#18]
I have **Cookies Samesite** workarounds for Chrome on Android
**Version _(that I test)_:** ` Chrome Beta 86.0.4240.75`
**Device:** `Redmi Note 8 running Android 9.0`

**Workarounds**

> Please note that doing this may make your browser less secure and it is not recommended.
This workaround is only working for now and may not work in future updates of Chrome.

1. Go to `chrome://flags`

![image](https://user-images.githubusercontent.com/38764429/96020990-06a15480-0e79-11eb-991f-48480d87fb5e.png)

2. Search `SameSite`

![image](https://user-images.githubusercontent.com/38764429/96021109-305a7b80-0e79-11eb-9a9e-864c1633bff5.png)

3. **Disable** `SameSite by default cookies` and `Cookies without SameSite must be secure`

![image](https://user-images.githubusercontent.com/38764429/96021181-45cfa580-0e79-11eb-9e37-23a6ff18d4ea.png)

4. Restart Chrome

![image](https://user-images.githubusercontent.com/38764429/96021283-68fa5500-0e79-11eb-8acf-0c7b2d6599cb.png)

5. Try refresh `e-hentai-view` website again

**Result**

![image](https://user-images.githubusercontent.com/38764429/96022776-91834e80-0e7b-11eb-93f6-05e70429b0c0.png)
![image](https://user-images.githubusercontent.com/38764429/96022846-b4adfe00-0e7b-11eb-9d92-bed7b668b5ae.png)

**Comment by aeongdesu** [comment]
Thank you! <3 `Samsung Galaxy Note8 | Chrome Stable 86.0.4240.75` working too

I'll update faq for korean thanks xD

**Comment by Nicezki** [comment]
> Thank you! <3 `Samsung Galaxy Note8 | Chrome Stable 86.0.4240.75` working too
> 
> I'll update faq for korean thanks xD

I'm glad that this workaround also worked for you.
