### ISSUE TITLE
EH设置和标签管理出现重定向过多问题

### ISSUE THREAD

**Issue by pboymt** [IronKinoko/e-hentai-view#23]
新Edge87，不清楚是不是浏览器自己的锅，后面又出现了图片疯狂在页面上闪烁然后被403的情况，不知道是不是那个地方的逻辑写出问题了。

**Comment by IronKinoko** [comment]
我edge87没有发现这个问题, 这个先放着吧😄😄😄

你能提供下具体怎么操作嘛?
