### ISSUE TITLE
希望能增加切换图片缩放模式的功能

### ISSUE THREAD

**Issue by dakkor** [IronKinoko/e-hentai-view#36]
目前的图片浏览模式只能根据图片宽度缩放，在使用从左到右或者从右到左的浏览模式的时候，会出现图片上下部分需要滑动才能显示出来的情况。希望能增加根据图片高度缩放与根据宽度与高度同时缩放的功能，十分感谢。

**Comment by IronKinoko** [comment]
好的，有空我会加上的，近期可能没空😓

在 ***@***.***> 写道：

**Comment by IronKinoko** [comment]
已完成

**Comment by dakkor** [comment]
请问缩放模式在哪里切换？我在浏览页面的设置里面还是只看到了阅读方向，没有缩放模式

**Comment by IronKinoko** [comment]
版本4.1.0 阅读界面的右上角设置按钮会出现选项

dakkor ***@***.***> 于2021年11月17日周三 下午10:13写道：

**Comment by dakkor** [comment]
![IMG_2684](https://user-images.githubusercontent.com/5956036/142221842-a756d697-bb09-49d5-a607-e12965d93de8.jpeg)
![IMG_2685](https://user-images.githubusercontent.com/5956036/142221858-d2edc914-29d3-414f-aa04-11e552979eba.jpeg)

我这边好像没看到有缩放的选项

**Comment by IronKinoko** [comment]
好吧，似乎当时设计的时候并没有提供控制开关，我记岔了。
目前是左右滑动模式下自动根据的宽/高显示一个合适比例，保证一张图在一个屏幕内完全显示

**Comment by dakkor** [comment]
感觉还是加个开关比较好，目前我感觉还是会有需要拖动才能看全图的情况。不管怎么说，辛苦大佬了。
