### ISSUE TITLE
更新版本后无法登陆

### ISSUE THREAD

**Issue by dakkor** [IronKinoko/e-hentai-view#37]
版本更新到4.1.0以后就没法登陆了，输入用户名密码之后一直转圈圈登陆不进去，直接用ex网页版可以看。ios版本是14.8

**Comment by IronKinoko** [comment]
我 4.1.0 登录功能挺正常的，或许是当时的网络问题？
如果能把 docker 输出的 log 贴出来就能帮忙看看是什么问题了

**Comment by dakkor** [comment]
docker的日志如下
POST -> /api/user/login
Error: connect ETIMEDOUT 157.240.17.50:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '157.240.17.50',
  port: 443,
  config: {
      url: 'https://exhentai.org/uconfig.php',
   （request配置部分略）
     ……
     toJSON: [Function: toJSON]
}

**Comment by IronKinoko** [comment]
初步看是网络不通，可能docker没有翻墙，连不上exhentai
你是通过哪种方式翻墙的？

- 路由器翻墙

这种方式一般不会出现docker连不了ex的问题

- 手机/pc 等翻墙

如果你是在手机端开启的翻墙，你pc没有开启的话，你的docker没有梯子，服务端(e-hentai-view) 就连不上exhentai了

以上只是猜测，从报错上看是网络问题
可以试试pc端全局代理，看看还会不会出现这种情况
