### ISSUE TITLE
Thumbnails are not showing

### ISSUE THREAD

**Issue by napqin** [IronKinoko/e-hentai-view#41]
I can view any galleries without issue, what bothering me is all thumbnails are not showing but alt texts.
This happen on my devices using iOS Safari, iOS Edge, Android KiwiBrowser.

Docker image hosted on my own NAS (local network)

**Comment by IronKinoko** [comment]
**android** 
#18

**ios** 
https://github.com/IronKinoko/e-hentai-view/blob/master/translations/en/FAQ.md#1-ios-can-not-see-the-picture

**pc chrome/edge**
https://github.com/IronKinoko/e-hentai-view/blob/master/translations/en/FAQ.md#4-windows-browser-cant-see-pictures

**mac** 
https://github.com/IronKinoko/e-hentai-view/blob/master/translations/en/FAQ.md#3-mac-system-safari-browser-can-not-see-the-picture

**Comment by napqin** [comment]
Ops, didn't check that out.
After ticking that and reinitiating PWA, now it works!
Thanks for your rapid assistance, and those awesome contribution you have made!
