### ISSUE TITLE
部署后无法登陆

### ISSUE THREAD

**Issue by lilifan105** [IronKinoko/e-hentai-view#42]
我在NAS里用docker部署完后，无法成功登陆
我没有能够访问exhentai的账号，我只需要访问ehentai，
我按照步骤先登陆ehentai，然后跳过了exhentai，最后输入账号密码后无反应。
尝试用cookie登陆，但是找不到igneous这个值

log截图如下
<img width="749" alt="屏幕快照 2022-07-20 的 17 20 59 下午" src="https://user-images.githubusercontent.com/83329310/179933703-1ee4bd9d-b680-4014-87ed-60b0069a65ba.png">

**Comment by IronKinoko** [comment]
非常抱歉，项目最初只为exhentai里站设计，没有考虑e-hentai。无法登录exhentai的话，使用不了这个项目

**Comment by lilifan105** [comment]
> 

了解了，那我还是尝试去注册一个exhentai账号好了，谢谢回答
