### ISSUE TITLE
您好，正在学习您的代码，想请教几个问题

### ISSUE THREAD

**Issue by KoriIku** [IronKinoko/e-hentai-view#44]
因为没有翻到联系方式只好在这里问了，抱歉。

第一，看起来图片都是在server上请求的，先通过/api/gallery/loadImg拿到一个src地址，再通过'/api/gallery/img?url=' + src)这个接口让服务器加载图片，是这样吗？

那么为什么不让服务器一次性请求到地址后直接请求图片再返回，而要设计两个接口呢？

readme中提到“项目需要翻墙访问，但ex的图片无需翻墙。”但是图片都是在服务端请求的，为什么不用翻墙呢？还是说图片其实是在本地请求的？

第二点是，为什么服务端有编写登陆的请求，为什么不直接在服务端登录然后返回cookie，而要在本地通过网页登陆呢？

期待您能解答一下这两个疑惑，多谢大佬。

**Comment by IronKinoko** [comment]
> 那么为什么不让服务器一次性请求到地址后直接请求图片再返回，而要设计两个接口呢？

1. `/api/gallery/loadImg` 这个获取图片，`/api/gallery/img` 解析图片返回base64
2. 获取的图片链接有时效性，15分钟左右链接就过期了
3. 拆成两个是因为 `/api/gallery/loadImg` 获取的是 URL + retryURL，图片加载失败可以换一张图片, `/api/gallery/img`只做解析图片

---

> readme中提到“项目需要翻墙访问，但ex的图片无需翻墙。”但是图片都是在服务端请求的，为什么不用翻墙呢？还是说图片其实是在本地请求的？

图片的服务和ex的服务是不同域名的，可能不用翻墙吧。我也不太确定，项目有些久了。真正使用起来的时候，都是挂梯子

---

> 第二点是，为什么服务端有编写登陆的请求，为什么不直接在服务端登录然后返回cookie，而要在本地通过网页登陆呢？

1. 主要是解决 CORS(跨域) 问题。PAW应用终究还是一个web应用，没办法禁止 CORS
2. 本地登录有两步
  2.1. 去ex做登录，这一步设置 ex 域名下cookie
  2.2. 在 e-hentai-view 内再次登录，这一步是让 e-hentai-view 服务器记录用户的 cookie
3. 两步登录后，ex 网站内有 cookie，e-hentai-view 也有 cookie
4. 首页/画廊的预览图都是直接访问 ex 链接，没有做中转，都需要用到 ex 的 cookie
5. e-hentai-view 的 cookie 主要是做个用户登录态，并在后续使用 cookie 调用 ex 接口

**Comment by IronKinoko** [comment]
项目挺久没有维护了，有些地方现在看来不太合理。

应该在服务端写一个代理接口，把所有图片资源通过代理接口从服务端转发一遍，这样就不用去 ex 站内登录了。

**Comment by KoriIku** [comment]
感谢解答！

图片的服务和ex的服务是不同域名这个我了解，因为eh的图片是通过h@h的p2p网络加载的，我想知道的是，既然图片是从服务端返回的，那应该不存在“服务端需要梯子但图片不需要梯子”的情况？

上面这个问题我主要的疑问是，哪些请求是经过服务器中转的，哪些资源是从客户端直接访问的，应该是缩略图和封面从客户端直连，其他的都是经由服务端中转的，是这样吗？

关于缩略图没有中转这个，我也写了一些代码，是不是这样：封面和缩略图是可以跨源访问的所以就不做中转，而其他的需要做中转。

第二个问题的第 1 条，是不是这样：因为ex需要cookies才能访问，而缩略图和封面是直接访问的，所以本地也需要一份cookie才可以正常访问，那么本地的cookie只是为了访问缩略图和封面，是这样吗？

**Comment by KoriIku** [comment]
> 项目挺久没有维护了，有些地方现在看来不太合理。
> 
> 应该在服务端写一个代理接口，把所有图片资源通过代理接口从服务端转发一遍，这样就不用去 ex 站内登录了。

我大概能猜到您当时的想法，可能是发现封面图可以跨源访问，为了尽量减少一点服务器的负载就这么写了？

前段时间eh大改了翻页方式，不能直接使用页码跳页了，这个项目估计只能看到一页了。

**Comment by IronKinoko** [comment]
> 那应该不存在“服务端需要梯子但图片不需要梯子”的情况？

应该是都需要梯子的

> 关于缩略图没有中转这个，我也写了一些代码，是不是这样：封面和缩略图是可以跨源访问的所以就不做中转，而其他的需要做中转。

对的，只有大图做了中转，其他缩略图都是直接访问 ex 的，所以 ex 需要域名内也设置 cookie。

> 我大概能猜到您当时的想法，可能是发现封面图可以跨源访问，为了尽量减少一点服务器的负载就这么写了？

当时可能啥也没想， 只是看到大图用不了才做大图的中转。 

> 前段时间eh大改了翻页方式，不能直接使用页码跳页了，这个项目估计只能看到一页了。

嗯，很久没维护了，最近都是直接用 ex 网站，配合 [userscripts](https://github.com/IronKinoko/userscripts/tree/master/packages/e-hentai-infinite-scroll) 访问。

**Comment by KoriIku** [comment]
好的，非常感谢大佬解答！
