### ISSUE TITLE
请教一下是如何实现返回时不丢失列表位置的

### ISSUE THREAD

**Issue by KoriIku** [IronKinoko/e-hentai-view#45]
大佬您好，想请教一下您是如何实现返回时列表不重载的？我用 react-router 来跳转，每次返回到画廊列表的时候都重新加载。看了您的代码好像没做useHistory之类的处理，是用 next/link 来跳转的原因吗？
但是我看 next.js 是 ssr 架构下使用的，您这个客户端应该没用 SSR 吧？server 里面的代码都是请求数据和解析数据用的，也可以用 nextjs 吗。实在是有点迷惑了，希望大佬能够指点一下。

**Comment by IronKinoko** [comment]
全是客户端渲染的

next框架跳转路由时会自动恢复滚动条位置，react-router也有这功能

数据请求使用swr做的，它有数据缓存功能，所以返回列表后会先渲染缓存数据，可以让next恢复滚动条位置，同时还会发起新的请求去更新缓存数据

可以查询`路由缓存`了解更多相关知识

**Comment by KoriIku** [comment]
好的好的，感谢大佬。我昨天也是用了 SWR 但是一直不行所以才来问您，结果刚刚什么都没改试了下又可以了，好奇怪。
感谢大佬。
